services:
  # A Docker web service
  - type: web
    name: Ngrok
    env: docker
    repo: https://github.com/sembakokevin-oss/craxid
    region: singapore # Render region
    plan: free
    envVars:
      - key: PORT
        value: 22
      - key: NGROK_TOKEN
        value: 3HTO4awV1SUNUc7ItK0EefZOR0i_5p25sycyjdeDMxJ1EVP5J
      - key: REGION
        value: ap # Region Ngrok untuk Asia/Singapura